# Generated by Django 3.2.15 on 2023-05-02 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0023_allow_blank_solved_by_topic_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.TextField(verbose_name="url")),
                ("question", models.TextField(verbose_name="question")),
            ],
        ),
        migrations.CreateModel(
            name="SurveyAvailableChoice",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("choice", models.TextField(verbose_name="Choice")),
                ("counter", models.PositiveIntegerField(default=0, verbose_name="Counter")),
                (
                    "related_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forum.surveyquestion",
                        verbose_name="Related question",
                    ),
                ),
            ],
        ),
    ]
